config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:new, :create, :show]
  #resources :categories
  #resources :states
  #resources :ratings
  #resources :contacts, only: [:new, :create]
  #resources :visitors, only: [:new, :create]
  root to: 'reviews#new'
  get 'get_plate' => 'reviews#get_plate'
  get 'averages' => 'reviews#averages'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Look Up', get_plate_path('reviews') %></li>
<li><%# link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Damn Driver" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dd" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77778142-1', 'auto');
  ga('send', 'pageview');

</script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= image_tag("Damn.png") %>
      <%= image_tag("Driver.png") %>
      <div class="aligncenter" align="center" >
           <script type="text/javascript">
              amzn_assoc_ad_type = "banner";
        amzn_assoc_marketplace = "amazon";
        amzn_assoc_region = "US";
        amzn_assoc_placement = "assoc_banner_placement_default";
        amzn_assoc_campaigns = "automotive";
        amzn_assoc_banner_type = "category";
        amzn_assoc_isresponsive = "true";
        amzn_assoc_banner_id = "1RFPP433RM54SE062N02";
        amzn_assoc_tracking_id = "eckelmeyer-20";
        amzn_assoc_linkid = "db1e2ec8bde7c9ebb0fcd5310f4cd2c5";
           </script>
           <script src="//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1"></script>
          </div>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>

    <p>Like us on Facebook</p>
    <p>
      <%= link_to 'https://www.facebook.com/DamnDriver' do %>
      <%= image_tag "facebook.png" %>
      <% end %>
    </p>


    <p></p>

  </body>
</html>